
-- 문제 1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD')  입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ;


-- 문제 2
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___' ;


-- 문제 3
SELECT PROFESSOR_NAME 교수이름, 
	FLOOR(MONTHS_BETWEEN(SYSDATE , TO_DATE('19'||SUBSTR(PROFESSOR_SSN ,1,6), 'RRRRMMDD'))/12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8 , 1)  = '1'
ORDER BY 	FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN ,1,6), 'RRRRMMDD'))/12) ;


-- 문제 4
SELECT SUBSTR(PROFESSOR_NAME, 2,2)
FROM TB_PROFESSOR;


-- 문제 5
SELECT STUDENT_NO , STUDENT_NAME  
FROM TB_STUDENT
WHERE NOT (FLOOR(MONTHS_BETWEEN(ENTRANCE_DATE  , 
		TO_DATE('19'||SUBSTR(STUDENT_SSN  ,1,6), 'RRRRMMDD'))/12) + 1) = 19;


-- 문제 6
SELECT TO_CHAR(TO_DATE('20201225', 'YYYYMMDD'), 'DAY') 요일  
FROM DUAL;
	

-- 문제 7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY"년 "MM"월" DD"일 "DAY'), TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY"년 "MM"월" DD"일 "DAY'),
		TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'RRRR"년 "MM"월" DD"일 "DAY'), TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'RRRR"년 "MM"월" DD"일 "DAY')
FROM DUAL;

-- 문제 8
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 문제 9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO IN 'A517178';

-- 문제 10
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO 
ORDER BY DEPARTMENT_NO;

-- 문제 11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;


-- 문제 12
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY SUBSTR(TERM_NO, 1, 4);


-- 문제 13
SELECT DEPARTMENT_NO, 
	SUM(
	CASE
		WHEN ABSENCE_YN = 'Y' THEN  1
	ELSE 0
	END
	) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ;

-- 문제 14
SELECT STUDENT_NAME 동일이름, COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2;


-- 문제 15
SELECT NVL(SUBSTR(TERM_NO, 1,4), ' ') 년도 , NVL(SUBSTR(TERM_NO, 5,2), ' ') 학기, ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1,4), SUBSTR(TERM_NO, 5,2))
ORDER BY SUBSTR(TERM_NO, 1,4);

SELECT *
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';


